version: 2
jobs:
  release:
    docker:
      - image: circleci/node:17.2
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn release
workflows:
  version: 2
  release-workflow:
    jobs:
      - release:
          context: semantic-release
          filters:
            branches:
              only: master
